# Generated by Django 3.0 on 2020-10-02 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('image_url', models.URLField(null=True)),
                ('address', models.CharField(choices=[('Toshkent', 'Toshkent'), ('Sirdaryo', 'Sirdaryo'), ('Jizzax', 'Jizzax'), ('Samarqand', 'Samarqand'), ('Buxoro', 'Buxoro'), ('Qashqadaryo', 'Qashqadaryo'), ('Navoiy', 'Navoiy'), ('Surxondaryo', 'Surxondaryo'), ('Namangan', 'Namangan'), ('Andijon', 'Andijon'), ("Farg'ona", "Farg'ona"), ('Xorazm', 'Xorazm'), ("Qoraqalpog'iston Res.", "Qoraqalpog'iston Res.")], max_length=10000, null=True)),
                ('contact_phone', models.CharField(max_length=200, null=True)),
                ('contact_email', models.EmailField(max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('parent_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Ayirboshlash', 'Ayirboshlash'), ('Bepul', 'Bepul'), ('Narx', 'Narx')], max_length=100, null=True)),
                ('valute', models.CharField(choices=[('sum', 'sum'), ('y.e.', 'y.e.')], max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('model', models.CharField(choices=[('Artel', 'Artel'), ('Alcatel-Lucent', 'Alcatel-Lucent'), ('Apple', 'Apple'), ('ASUS', 'ASUS'), ('BlackBerry', 'BlackBerry'), ('Fly', 'Fly'), ('Google', 'Google'), ('HTC', 'HTC'), ('Huawei', 'Huawei'), ('Lenovo', 'Lenovo'), ('LG', 'LG'), ('Meizu', 'Meizu'), ('Mio', 'Mio'), ('Motorola', 'Motorola'), ('Nokia', 'Nokia'), ('Pantech', 'Pantech'), ('Samsung', 'Samsung'), ('Sony', 'Sony'), ('Sony Ericsson', 'Sony Ericsson'), ('Vertu', 'Vertu'), ('Xiaomi', 'Xiaomi'), ('Boshqa marka', 'Boshqa marka')], max_length=100, null=True)),
                ('seller', models.CharField(choices=[('Jismoniy shaxs', 'Jismoniy shaxs'), ('Yuridik shaxs', 'Yuridik shaxs')], max_length=100, null=True)),
                ('condition', models.CharField(choices=[('Ishlatilgan', 'Ishlatilgan'), ('Yangi', 'Yangi')], max_length=100, null=True)),
                ('parent_product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.ProductParent')),
            ],
        ),
        migrations.AddField(
            model_name='productparent',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.SubCategory'),
        ),
        migrations.AddField(
            model_name='productparent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valute', models.CharField(choices=[('sum', 'sum'), ('y.e.', 'y.e.')], max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('rooms_num', models.IntegerField(null=True)),
                ('total_area', models.IntegerField(null=True)),
                ('living_area', models.IntegerField(null=True)),
                ('location', models.CharField(choices=[('Shaharda', 'Shaharda'), ('Shahar atrofida', 'Shahar atrofida'), ('Qishloq joylarida', 'Qishloq joylarida'), ('Trassa chetida', 'Trassa chetida'), ('Suv havzasi, daryo yaqinida', 'Suv havzasi, daryo yaqinida'), ("Tog' etagida", "Tog' etagida"), ('Dalahovli hududida', 'Dalahovli hududida'), ('Yopiq hududda', 'Yopiq hududda')], max_length=100, null=True)),
                ('floors_num', models.IntegerField(null=True)),
                ('ceil_height', models.IntegerField(null=True)),
                ('with_furniture', models.BooleanField(null=True)),
                ('condition', models.CharField(choices=[('Mualliflik loyihasi', 'Mualliflik loyihasi'), ('Evrotaʼmir', 'Evrotaʼmir'), ('Oʻrtacha', 'Oʻrtacha'), ('Taʼmir talab', 'Taʼmir talab'), ('Qora suvoq', 'Qora suvoq'), ('Tozalashdan avvalgi pardoz', 'Tozalashdan avvalgi pardoz'), ('Qora suvoq', 'Qora suvoq'), ('Buziladigan', 'Buziladigan')], max_length=100, null=True)),
                ('house_type', models.CharField(choices=[('Uy', 'Uy'), ('Fligel', 'Fligel'), ('Kottej', 'Kottej'), ('Uyning bir qismi', 'Uyning bir qismi'), ('Dala hovli', 'Dala hovli'), ('Tounxaus', 'Tounxaus')], max_length=100, null=True)),
                ('building_type', models.CharField(choices=[("G'ishtli", "G'ishtli"), ('Panelli', 'Panelli'), ('Monolitli', 'Monolitli'), ('Blokli', 'Blokli'), ("Yog'och", "Yog'och")], max_length=100, null=True)),
                ('water_support', models.CharField(choices=[('Uyda', 'Uyda'), ('Markazlashgan suv taʼminoti', 'Markazlashgan suv taʼminoti'), ('Oʻtkazish imkoniyati', 'Oʻtkazish imkoniyati'), ('Uchastkada quduq', 'Uchastkada quduq'), ('Chekkasida', 'Chekkasida'), ('Quduq', 'Quduq'), ('Yoʻq', 'Yoʻq')], max_length=100, null=True)),
                ('electricity_support', models.CharField(choices=[('Bor', 'Bor'), ('Ulanish imkoniyati bor', 'Ulanish imkoniyati bor'), ('Yoʻq', 'Yoʻq')], max_length=100, null=True)),
                ('heating_support', models.CharField(choices=[('Markazlashgan', 'Markazlashgan'), ('Gazda', 'Gazda'), ('Qattiq yoqilgʻida', 'Qattiq yoqilgʻida'), ('Suyuq yoqilgʻida', 'Suyuq yoqilgʻida'), ('Elektrda', 'Elektrda'), ('Aralash', 'Aralash'), ('Isitkichsiz', 'Isitkichsiz')], max_length=100, null=True)),
                ('gas_support', models.CharField(choices=[('Magistral', 'Magistral'), ('Alohida', 'Alohida'), ('Ulanish imkoniyati bor', 'Ulanish imkoniyati bor'), ('Yoʻq', 'Yoʻq')], max_length=100, null=True)),
                ('in_house', models.CharField(max_length=100, null=True)),
                ('around_house', models.CharField(max_length=100, null=True)),
                ('seller', models.CharField(choices=[('Jismoniy shaxs', 'Jismoniy shaxs'), ('Yuridik shaxs', 'Yuridik shaxs')], max_length=100, null=True)),
                ('parent_product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.ProductParent')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Ayirboshlash', 'Ayirboshlash'), ('Narx', 'Narx')], max_length=100, null=True)),
                ('currency', models.CharField(choices=[('sum', 'sum'), ('y.e.', 'y.e.')], max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('model', models.CharField(choices=[('Chevrolet', 'Chevrolet'), ('Daewoo', 'Daewoo'), ('Mercedes', 'Mercedes'), ('Bmw', 'Bmw'), ('Vaz', 'Vaz'), ('Toyota', 'Toyota'), ('Hyudai', 'Hyudai'), ('Opel', 'Opel'), ('Ford', 'Ford'), ('Nissan', 'Nissan'), ('Audi', 'Audi'), ('Kia', 'Kia'), ('Fiat', 'Fiat'), ('Mazda', 'Mazda'), ('Lexus', 'Lexus'), ('Volkswagen', 'Volkswagen'), ('Mitsubishi', 'Mitsubishi'), ('Gaz', 'Gaz'), ('Moskvich', 'Moskvich'), ('Uaz', 'Uaz'), ('Zaz', 'Zaz'), ('Izh', 'Izh'), ('Boshqalar', 'Boshqalar')], max_length=100, null=True)),
                ('production_year', models.IntegerField(null=True)),
                ('transmission', models.CharField(choices=[('Mexanik', 'Mexanik'), ('Avtomatik', 'Avtomatik'), ('Boshqa', 'Boshqa')], max_length=100, null=True)),
                ('fuel_type', models.CharField(choices=[('Benzin', 'Benzin'), ('Dizel', 'Dizel'), ('Boshqa', 'Boshqa')], max_length=100, null=True)),
                ('engine_size', models.FloatField(null=True)),
                ('way_length', models.IntegerField(null=True)),
                ('condition', models.CharField(choices=[('Ideal', 'Ideal'), ('Yaxshi', 'Yaxshi'), ("O'rta", "O'rta"), ("Ta'mir talab", "Ta'mir talab")], max_length=100, null=True)),
                ('seller', models.CharField(choices=[('Jismoniy shaxs', 'Jismoniy shaxs'), ('Yuridik shaxs', 'Yuridik shaxs')], max_length=100, null=True)),
                ('parent_product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.ProductParent')),
            ],
        ),
    ]
