# Generated by Django 3.0.8 on 2020-10-02 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcar',
            old_name='currency',
            new_name='valute',
        ),
    ]
