# Generated by Django 3.0.8 on 2020-10-03 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201003_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFurniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=100, null=True)),
                ('valute', models.CharField(choices=[('sum', 'sum'), ('y.e.', 'y.e.')], max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('furniture_type', models.CharField(choices=[('Mehmonxona uchun mebel', 'Mehmonxona uchun mebel'), ('Yotoqxona uchun mebel', 'Yotoqxona uchun mebel'), ('Dahliz uchun mebel', 'Dahliz uchun mebel'), ('Oshxona mebeli', 'Oshxona mebeli'), ('Ofis mebeli', 'Ofis mebeli'), ("Bog' mebeli", "Bog' mebeli"), ('Maxsus mebel', 'Maxsus mebel')], max_length=100, null=True)),
                ('condition', models.CharField(choices=[('Ishlatilgan', 'Ishlatilgan'), ('Yangi', 'Yangi')], max_length=100, null=True)),
                ('seller', models.CharField(choices=[('Jismoniy shaxs', 'Jismoniy shaxs'), ('Yuridik shaxs', 'Yuridik shaxs')], max_length=100, null=True)),
                ('parent_product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.ProductParent')),
            ],
        ),
    ]
