# Generated by Django 3.0.8 on 2020-10-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productfurniture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfurniture',
            name='payment_method',
            field=models.CharField(choices=[('Ayirboshlash', 'Ayirboshlash'), ('Bepul', 'Bepul'), ('Narx', 'Narx')], max_length=100, null=True),
        ),
    ]
