# Generated by Django 3.0.8 on 2020-10-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201003_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcar',
            name='engine_size',
            field=models.IntegerField(null=True),
        ),
    ]
