# Generated by Django 3.0.8 on 2020-10-09 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201009_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProgrammerWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Ayirboshlash', 'Ayirboshlash'), ('Bepul', 'Bepul'), ('Narx', 'Narx')], max_length=100, null=True)),
                ('valute', models.CharField(choices=[('sum', 'sum'), ('y.e.', 'y.e.')], max_length=100, null=True)),
                ('work_type', models.CharField(choices=[('Taklif qilaman', 'Taklif qilaman'), ('Izlayapman', 'Izlayapman')], max_length=100, null=True)),
                ('time', models.CharField(choices=[('Doimiy bandlik', 'Doimiy bandlik'), ('Vaqtinchalik bandlik', 'Vaqtinchalik bandlik')], max_length=100, null=True)),
                ('price_from', models.IntegerField(blank=True, null=True)),
                ('price_to', models.IntegerField(blank=True, null=True)),
                ('employment', models.CharField(choices=[('To‘liq stavkada bandlik', 'To‘liq stavkada bandlik'), ('To‘liq bo‘lmagan bandlik', 'To‘liq bo‘lmagan bandlik')], max_length=100, null=True)),
                ('is_online_work', models.BooleanField(null=True)),
                ('portfolio_url', models.URLField(null=True)),
                ('seller', models.CharField(choices=[('Jismoniy shaxs', 'Jismoniy shaxs'), ('Yuridik shaxs', 'Yuridik shaxs')], max_length=100, null=True)),
                ('parent_product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.ProductParent')),
            ],
        ),
    ]
