# Generated by Django 3.0.8 on 2020-10-10 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20201010_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductApartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=100, null=True)),
                ('valute', models.CharField(choices=[('sum', 'sum'), ('y.e.', 'y.e.')], max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('house_type', models.CharField(choices=[('Yangi qurilgan uylar', 'Yangi qurilgan uylar'), ('Ikkilamchi bozor', 'Ikkilamchi bozor')], max_length=100, null=True)),
                ('rooms_num', models.IntegerField(null=True)),
                ('total_area', models.IntegerField(null=True)),
                ('living_area', models.IntegerField(null=True)),
                ('kitchen_area', models.IntegerField(null=True)),
                ('floor', models.IntegerField(null=True)),
                ('total_floor', models.IntegerField(null=True)),
                ('building_type', models.CharField(choices=[("G'ishtli", "G'ishtli"), ('Panelli', 'Panelli'), ('Monolitli', 'Monolitli'), ('Blokli', 'Blokli'), ("Yog'och", "Yog'och")], max_length=100, null=True)),
                ('plan', models.CharField(choices=[('Aralash', 'Aralash'), ('Alohida ajratilgan', 'Alohida ajratilgan'), ('Aralash-alohida', 'Aralash-alohida'), ('Studiya', 'Studiya'), ('Pentxaus', 'Pentxaus'), ("Ko'p darajali", "Ko'p darajali"), ('Kichik oilalar uchun', 'Kichik oilalar uchun')], max_length=100, null=True)),
                ('construction_year', models.IntegerField(null=True)),
                ('sanuzel', models.CharField(choices=[('Alohida', 'Alohida'), ('Aralash', 'Aralash'), ("2 va undan ko'p", "2 va undan ko'p")], max_length=100, null=True)),
                ('with_furniture', models.BooleanField(null=True)),
                ('ceil_height', models.IntegerField(null=True)),
                ('in_house', models.CharField(max_length=10000, null=True)),
                ('around_house', models.CharField(max_length=10000, null=True)),
                ('condition', models.CharField(choices=[('Mualliflik loyihasi', 'Mualliflik loyihasi'), ('Evrotaʼmir', 'Evrotaʼmir'), ('Oʻrtacha', 'Oʻrtacha'), ('Taʼmir talab', 'Taʼmir talab'), ('Qora suvoq', 'Qora suvoq'), ('Tozalashdan avvalgi pardoz', 'Tozalashdan avvalgi pardoz'), ('Buziladigan', 'Buziladigan')], max_length=100, null=True)),
                ('seller', models.CharField(choices=[('Jismoniy shaxs', 'Jismoniy shaxs'), ('Yuridik shaxs', 'Yuridik shaxs')], max_length=100, null=True)),
                ('parent_product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.ProductParent')),
            ],
        ),
    ]
